trigger:
- master
variables:
- group: Dev

stages:
- stage: build
  jobs:
  - job: 'BuildAndPublish'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
    - task: AzureFileCopy@4
      displayName: 'AzureBlob File Copy'
      inputs:
        SourcePath: Dev/vnet.parameters.json
        azureSubscription: $(serviceConnection)
        Destination: AzureBlob
        storage: tempsafgc
        ContainerName: blob
      enabled: false

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM Template deployment: Resource Group scope'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployVnet.json
        csmParametersFile: Dev/vnet.parameters.json
        deploymentMode: Validation

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM Template deployment: Resource Group scope'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployNSG.json
        csmParametersFile: Dev/NSG.parameters.json
        deploymentMode: Validation

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Blob Storage via ARM Templates'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployBlobStorage.json
        csmParametersFile: Dev/blobStorage.parameters.json
        deploymentMode: Validation

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Table Storage via ARM Templates'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployTableSA.json
        csmParametersFile: Dev/tableStorage.parameters.json
        deploymentMode: Validation

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy AKS Cluster'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        overrideParameters: -existingServicePrincipalClientId $(SPNClientID) -existingServicePrincipalClientSecret $(SPNSecret) -existingServicePrincipalObjectId $(SPNObjectID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployAKS.json
        csmParametersFile: Dev/aks.parameters.json
        deploymentMode: Validation

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy WAF'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployWAF.json
        csmParametersFile: Dev/waf.parameters.json
        deploymentMode: Validation

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifact: 'CloudEng-$(Build.BuildNumber)'

- stage: deploy
  jobs:
  - job: 'deployInfrastructure'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
    - task: AzureFileCopy@4
      displayName: 'AzureBlob File Copy'
      inputs:
        SourcePath: Dev/vnet.parameters.json
        azureSubscription: $(serviceConnection)
        Destination: AzureBlob
        storage: tempsafgc
        ContainerName: blob
      enabled: false

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy VNET and Subnets via ARM Template deployment'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployVnet.json
        csmParametersFile: Dev/vnet.parameters.json
        deploymentMode: Incremental
      enabled: false
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy NSGs via ARM Templates'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployNSG.json
        csmParametersFile: Dev/NSG.parameters.json
        deploymentMode: Incremental

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Blob Storage via ARM Templates'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployBlobStorage.json
        csmParametersFile: Dev/blobStorage.parameters.json
        deploymentMode: Incremental

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Table Storage via ARM Templates'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deploytableSA.json
        csmParametersFile: Dev/tableStorage.parameters.json
        deploymentMode: Incremental

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy AKS Cluster'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        overrideParameters: -existingServicePrincipalClientId $(SPNClientID) -existingServicePrincipalClientSecret $(SPNSecret) -existingServicePrincipalObjectId $(SPNObjectID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployAKS.json
        csmParametersFile: Dev/aks.parameters.json
        deploymentMode: Incremental

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy WAF'
      inputs:
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionID)
        resourceGroupName: 'ssuse-cloudeng01-rg'
        location: 'East US'
        csmFile: Templates/deployWAF.json
        csmParametersFile: Dev/waf.parameters.json
        deploymentMode: Incremental



